import 'package:flutter/material.dart';
import '../services/api_client.dart';
import '../services/local_db.dart';
import 'operation_form_screen.dart';
import 'procurement_screen.dart';

class HomeScreen extends StatefulWidget { final ApiClient? api; const HomeScreen({super.key,this.api}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  late final ApiClient api;
  @override void initState(){ api=widget.api ?? ApiClient(baseUrl: const String.fromEnvironment('API_URL', defaultValue: 'http://127.0.0.1:8000')); super.initState(); _load(); }
  Map<String,dynamic>? summary; int pending=0; bool online=false;
  Future<void> _load() async { await api.syncPending(); final s=await api.getObject('dashboard/summary'); final o=await api.health(); final p=await LocalDb.instance.pendingCount(); if(mounted)setState(()=>{summary=s,online=o,pending=p}); }
  void _open(String title, Widget page){Navigator.push(context, MaterialPageRoute(builder:(_)=>page)).then((_){_load();});}
  @override Widget build(BuildContext context){
    final modules=[('الهيكل الزراعي',Icons.account_tree,StructureScreen(api:api)),('الصوب ودورات المحاصيل',Icons.eco,CyclesScreen(api:api)),('المخزون',Icons.inventory_2,InventoryScreen(api:api)),('المشتريات',Icons.shopping_cart,ProcurementScreen(api:api)),('المبيعات المحلية',Icons.storefront,SimpleModule(title:'المبيعات المحلية',icon:Icons.storefront)),('التصدير',Icons.local_shipping,SimpleModule(title:'التصدير',icon:Icons.local_shipping)),('المحاسبة',Icons.account_balance,SimpleModule(title:'المحاسبة',icon:Icons.account_balance)),('التقارير',Icons.analytics,SimpleModule(title:'التقارير',icon:Icons.analytics))];
    return Scaffold(appBar:AppBar(title:const Text('Agri ERP'),actions:[Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Chip(label:Text(online?'متصل':'غير متصل'),avatar:Icon(online?Icons.cloud_done:Icons.cloud_off,size:18))),IconButton(onPressed:_load,icon:const Icon(Icons.sync))]),body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[_stats(),const SizedBox(height:18),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:220,childAspectRatio:1.35,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:modules.length,itemBuilder:(_,i)=>Card(child:InkWell(onTap:()=>_open(modules[i].$1,modules[i].$3),borderRadius:BorderRadius.circular(16),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(modules[i].$2,size:38),const SizedBox(height:8),Text(modules[i].$1,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w600))]))))])),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_open('تسجيل عملية',OperationFormScreen(api:api)),icon:const Icon(Icons.add_task),label:const Text('عملية زراعية')),bottomNavigationBar:pending>0?BottomAppBar(child:Padding(padding:const EdgeInsets.all(10),child:Text('عمليات تنتظر المزامنة: $pending'))):null);
  }
  Widget _stats(){final s=summary??{}; return Card(child:Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:18,runSpacing:12,children:[_stat('المزارع',s['farms']),_stat('الصوب',s['greenhouses']),_stat('دورات المحصول',s['crop_cycles']),_stat('الأصناف',s['items']),_stat('أوامر البيع',s['sales_orders'])])));}
  Widget _stat(String n,d)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(fontSize:12)),Text('${d??0}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold))]);
}

class StructureScreen extends StatefulWidget{final ApiClient api; const StructureScreen({super.key,required this.api}); @override State<StructureScreen> createState()=>_StructureScreenState();}
class _StructureScreenState extends State<StructureScreen>{Map<String,List<dynamic>> data={}; @override void initState(){super.initState();_load();} Future<void> _load()async{final r={for(final e in ['sectors','farms','clusters','greenhouses']) e:await widget.api.getList(e)};if(mounted)setState(()=>data=r);} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الهيكل الزراعي')),body:ListView(padding:const EdgeInsets.all(12),children:[_section('القطاعات',data['sectors']??[]),_section('المزارع',data['farms']??[]),_section('Clusters',data['clusters']??[]),_section('الصوب',data['greenhouses']??[])])); Widget _section(String t,List<dynamic> xs)=>ExpansionTile(title:Text('$t (${xs.length})'),children:xs.take(100).map((x)=>ListTile(title:Text('${x['name']??x['code']??x['id']??''}'),subtitle:Text('${x['code']??''}'))).toList());}

class CyclesScreen extends StatefulWidget{final ApiClient api; const CyclesScreen({super.key,required this.api}); @override State<CyclesScreen> createState()=>_CyclesScreenState();}
class _CyclesScreenState extends State<CyclesScreen>{List<dynamic> xs=[]; @override void initState(){super.initState();_load();} Future<void> _load()async{final r=await widget.api.getList('crop-cycles');if(mounted)setState(()=>xs=r);} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('دورات المحاصيل')),body:ListView.builder(itemCount:xs.length,itemBuilder:(_,i){final x=xs[i];return Card(child:ListTile(leading:const Icon(Icons.spa),title:Text('${x['name']??'دورة'}'),subtitle:Text('الصوبة: ${x['greenhouse_id']??'-'}')));}));}

class InventoryScreen extends StatefulWidget{final ApiClient api; const InventoryScreen({super.key,required this.api}); @override State<InventoryScreen> createState()=>_InventoryScreenState();}
class _InventoryScreenState extends State<InventoryScreen>{List<dynamic> xs=[];List<dynamic> stock=[]; @override void initState(){super.initState();_load();} Future<void> _load()async{final r=await widget.api.getList('items');final s=await widget.api.getList('inventory/stock-summary');if(mounted)setState((){xs=r;stock=s;});} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('المخزون')),body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(12),children:[const Text('أرصدة المخزون',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...stock.take(100).map((x)=>Card(child:ListTile(leading:Icon(x['status']=='OK'?Icons.check_circle:Icons.warning),title:Text('${x['item']??''} - ${x['warehouse']??''}'),subtitle:Text('الرصيد: ${x['balance']??0} ${x['unit']??''} | الحد الأدنى: ${x['min_stock']??0} | إعادة الطلب: ${x['reorder_level']??0}')))),const SizedBox(height:12),const Text('الأصناف',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...xs.take(100).map((x)=>ListTile(leading:const Icon(Icons.inventory_2),title:Text('${x['name']??''}'),subtitle:Text('الوحدة: ${x['unit']??'-'} | حد الطلب: ${x['reorder_level']??0}')))])));}
}

class SimpleModule extends StatelessWidget{final String title;final IconData icon;const SimpleModule({super.key,required this.title,required this.icon});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:72),const SizedBox(height:16),Text('واجهة ${title} قيد التوسعة في الإصدار التالي.'),const SizedBox(height:8),const Text('الـAPI الأساسي جاهز للعمل.')]));}
