import 'package:flutter/material.dart';
import '../services/api_client.dart';

class ProcurementScreen extends StatefulWidget {
  final ApiClient api;
  const ProcurementScreen({super.key, required this.api});
  @override State<ProcurementScreen> createState()=>_ProcurementScreenState();
}
class _ProcurementScreenState extends State<ProcurementScreen> {
  Map<String,List<dynamic>> data={};
  bool loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { setState(()=>loading=true); final keys=['suppliers','items','warehouses','purchase-quotations','purchase-orders','goods-receipts','purchase-invoices','inventory/issues','accounts']; final r=<String,List<dynamic>>{}; for(final k in keys){r[k]=await widget.api.getList(k);} if(mounted)setState(()=>{data=r,loading=false}); }
  @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('المشتريات والمخزون'),actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(12),children:[
    _card('عرض سعر جديد',Icons.request_quote,()=>_open(const _DocType.quotation)),
    _card('أمر شراء جديد',Icons.shopping_cart_checkout,()=>_open(const _DocType.order)),
    _card('إذن استلام',Icons.move_to_inbox,()=>_open(const _DocType.receipt)),
    _card('فاتورة شراء',Icons.receipt_long,()=>_open(const _DocType.invoice)),
    _card('إذن صرف',Icons.outbox,()=>_open(const _DocType.issue)),
    const SizedBox(height:8), _summary('عروض الأسعار','purchase-quotations'), _summary('أوامر الشراء','purchase-orders'), _summary('أذون الاستلام','goods-receipts'), _summary('فواتير الشراء','purchase-invoices'), _summary('أذون الصرف','inventory/issues'),
  ]));
  Widget _card(String title,IconData icon,VoidCallback onTap)=>Card(child:ListTile(leading:Icon(icon,size:32),title:Text(title,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:const Text('إدخال واعتماد المستند من التطبيق'),trailing:const Icon(Icons.chevron_left),onTap:onTap));
  Widget _summary(String title,String key){final xs=data[key]??[]; return Card(child:ExpansionTile(title:Text('$title (${xs.length})'),children:xs.take(15).map((x){final n=x['quotation_no']??x['order_no']??x['receipt_no']??x['issue_no']??x['id']; final sub=x['subtotal']??x['total_cost']??0; final vat=x['vat_amount']??0; final grand=x['grand_total']??sub; return ListTile(title:Text('$n'),subtitle:Text('الحالة: ${x['status']??'-'} | الصافي: $sub | VAT: $vat | الإجمالي: $grand'),trailing:(key=='purchase-invoices' && x['status']=='DRAFT')?IconButton(icon:const Icon(Icons.check_circle),tooltip:'اعتماد',onPressed:()async{final ok=await widget.api.post('purchase-invoices/${x['id']}/approve',{});if(ok)_load();}):null);}).toList()));}
  void _open(_DocType t){showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>_DocumentForm(api:widget.api,type:t,items:data['items']??[],suppliers:data['suppliers']??[],warehouses:data['warehouses']??[],quotations:data['purchase-quotations']??[],orders:data['purchase-orders']??[],accounts:data['accounts']??[],invoices:data['purchase-invoices']??[],onSaved:_load));}
}
enum _DocType { quotation, order, receipt, invoice, issue }
class _DocumentForm extends StatefulWidget { final ApiClient api; final _DocType type; final List<dynamic> items,suppliers,warehouses,quotations,orders,accounts,invoices; final VoidCallback onSaved; const _DocumentForm({required this.api,required this.type,required this.items,required this.suppliers,required this.warehouses,required this.quotations,required this.orders,required this.accounts,required this.invoices,required this.onSaved}); @override State<_DocumentForm> createState()=>_DocumentFormState(); }
class _DocumentFormState extends State<_DocumentForm>{
 final no=TextEditingController(),qty=TextEditingController(text:'1'),price=TextEditingController(text:'0'),vat=TextEditingController(text:'14'),batch=TextEditingController(),expiry=TextEditingController(); bool vatOn=true,saving=false; String? supplier,item,warehouse,quotation,order,vatAccount,receipt; 
 @override void dispose(){for(final c in [no,qty,price,vat,batch,expiry])c.dispose();super.dispose();}
 String get title=>switch(widget.type){_DocType.quotation=>'عرض سعر',_DocType.order=>'أمر شراء',_DocType.receipt=>'إذن استلام',_DocType.invoice=>'فاتورة شراء',_DocType.issue=>'إذن صرف'};
 Future<void> save() async {setState(()=>saving=true); final today=DateTime.now().toIso8601String().substring(0,10); final q=double.tryParse(qty.text)??0,p=double.tryParse(price.text)??0,v=double.tryParse(vat.text)??0; Map<String,dynamic> body;
   try {
    if(widget.type==_DocType.quotation){if(supplier==null||item==null)throw 'اختر المورد والصنف'; body={'supplier_id':supplier,'company_id':null,'quotation_no':no.text,'quotation_date':today,'currency':'EGP','exchange_rate':1,'vat_enabled':vatOn,'vat_rate':vatOn?v:0,'lines':[{'item_id':item,'quantity':q,'unit_price':p}]};}
    else if(widget.type==_DocType.order){if(supplier==null||item==null||warehouse==null)throw 'اختر المورد والصنف والمخزن'; body={'supplier_id':supplier,'company_id':null,'order_no':no.text,'order_date':today,'quotation_id':quotation,'currency':'EGP','exchange_rate':1,'vat_enabled':vatOn,'vat_rate':vatOn?v:0,'lines':[{'item_id':item,'warehouse_id':warehouse,'quantity':q,'unit_price':p}]};}
    else if(widget.type==_DocType.receipt){if(order==null||item==null)throw 'اختر أمر الشراء والصنف'; final lines=await widget.api.getList('purchase-orders/$order/lines'); if(lines.isEmpty)throw 'أمر الشراء لا يحتوي على أصناف'; body={'purchase_order_id':order,'receipt_no':no.text,'receipt_date':today,'lines':[{'purchase_order_line_id':lines.first['id'],'quantity':q,'unit_cost':p,'batch_no':batch.text.isEmpty?null:batch.text,'expiry_date':expiry.text.isEmpty?null:expiry.text}]};}
    else if(widget.type==_DocType.invoice){if(supplier==null||item==null)throw 'اختر المورد والصنف'; body={'supplier_id':supplier,'company_id':null,'invoice_no':no.text,'invoice_date':today,'currency':'EGP','exchange_rate':1,'vat_enabled':vatOn,'vat_rate':vatOn?v:0,'vat_account_id':vatAccount,'receipt_id':receipt,'lines':[{'item_id':item,'warehouse_id':warehouse,'quantity':q,'unit_cost':p}]};}
    else {if(item==null||warehouse==null)throw 'اختر الصنف والمخزن'; body={'issue_no':no.text,'issue_date':today,'warehouse_id':warehouse,'lines':[{'item_id':item,'quantity':q,'unit_cost':p}]};}
    // company_id is required by the backend. Prefer the first available company through a lightweight lookup; fallback to stored env is intentionally avoided.
    if(body['company_id']==null){final companies=await widget.api.getList('companies'); if(companies.isEmpty)throw 'لا توجد شركة معرفة في النظام'; body['company_id']=companies.first['id'];}
    final endpoint=switch(widget.type){_DocType.quotation=>'purchase-quotations',_DocType.order=>'purchase-orders',_DocType.receipt=>'goods-receipts',_DocType.invoice=>'purchase-invoices',_DocType.issue=>'inventory/issues'};
    final ok=await widget.api.post(endpoint,body); if(!ok)throw 'تعذر حفظ المستند'; if(mounted){Navigator.pop(context);widget.onSaved();ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تم حفظ $title')));}
   } catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'))));} finally {if(mounted)setState(()=>saving=false);}
 }
 @override Widget build(BuildContext c){return Padding(padding:EdgeInsets.only(left:16,right:16,top:16,bottom:MediaQuery.of(c).viewInsets.bottom+16),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[Expanded(child:Text('إضافة $title',style:Theme.of(c).textTheme.titleLarge)),IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.close))]),TextField(controller:no,decoration:const InputDecoration(labelText:'رقم المستند')),if(widget.type!=_DocType.issue&&widget.type!=_DocType.receipt)_drop('المورد',supplier,widget.suppliers,(x)=>x['id'].toString(),(x)=>x['name']??x['id'],(v)=>setState(()=>supplier=v)),if(widget.type==_DocType.receipt)_drop('أمر الشراء',order,widget.orders,(x)=>x['id'].toString(),(x)=>x['order_no']??x['id'],(v)=>setState(()=>order=v)),if(widget.type==_DocType.order)_drop('عرض السعر (اختياري)',quotation,widget.quotations,(x)=>x['id'].toString(),(x)=>x['quotation_no']??x['id'],(v)=>setState(()=>quotation=v)),_drop('الصنف',item,widget.items,(x)=>x['id'].toString(),(x)=>x['name']??x['code']??x['id'],(v)=>setState(()=>item=v)),if(widget.type!=_DocType.quotation&&widget.type!=_DocType.receipt)_drop('المخزن',warehouse,widget.warehouses,(x)=>x['id'].toString(),(x)=>x['name']??x['id'],(v)=>setState(()=>warehouse=v)),Row(children:[Expanded(child:TextField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'الكمية'))),const SizedBox(width:10),Expanded(child:TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السعر الصافي')))]),if(widget.type==_DocType.receipt||widget.type==_DocType.issue)TextField(controller:batch,decoration:const InputDecoration(labelText:'رقم التشغيلة (اختياري)')),if(widget.type==_DocType.receipt)TextField(controller:expiry,decoration:const InputDecoration(labelText:'تاريخ الصلاحية YYYY-MM-DD')),if(widget.type==_DocType.quotation||widget.type==_DocType.order||widget.type==_DocType.invoice)SwitchListTile(title:const Text('إضافة VAT'),subtitle:Text(vatOn?'الضريبة محسوبة منفصلة عن السعر الأصلي':'بدون ضريبة قيمة مضافة'),value:vatOn,onChanged:(v)=>setState(()=>vatOn=v)),if((widget.type==_DocType.quotation||widget.type==_DocType.order||widget.type==_DocType.invoice)&&vatOn)TextField(controller:vat,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'نسبة VAT %')),if(widget.type==_DocType.invoice&&vatOn)_drop('حساب VAT',vatAccount,widget.accounts,(x)=>x['id'].toString(),(x)=>'${x['code']??''} ${x['name']??''}',(v)=>setState(()=>vatAccount=v)),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:saving?null:save,icon:saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save),label:Text(saving?'جاري الحفظ...':'حفظ المستند'))])));}
 Widget _drop(String label,String? value,List<dynamic> xs,String Function(dynamic) val,String Function(dynamic) text,ValueChanged<String?> onChanged)=>DropdownButtonFormField<String>(value:value,decoration:InputDecoration(labelText:label),items:xs.map((x)=>DropdownMenuItem(value:val(x),child:Text(text(x)))).toList(),onChanged:onChanged);
}
